import type { Meta } from "../../../lib/meta";

export const meta: Meta = {
  slug: "range-brush",
  title: "Range Brush",
  category: "ui",
  description: "A two-handle numeric interval brush with ordered, stepped pointer and keyboard input.",
  tags: ["range", "interval", "brush", "slider", "ui"],
  facets: ["static", "interactive"],
  wave: 15,
  release: "components-2026-10-04",
  animated: false,
  decorative: false,
  host: "div",
  stage: "inline",
  palette: ["fg", "bg", "accent", "muted"],
  controlled: { value: "valueChange" },
  interactions: [
    [
      { step: "press", key: "Tab" },
      { step: "expectFocus", selector: "[data-part=\"lower\"]" },
      { step: "press", key: "ArrowRight" },
      { step: "expectEvent", name: "valueChange", detail: [26, 75] },
      { step: "expectAttr", selector: "[data-part=\"lower\"]", name: "aria-valuenow", value: "26" },
      { step: "press", key: "End" },
      { step: "expectEvent", name: "valueChange", detail: [75, 75] },
      { step: "expectAttr", selector: "[data-part=\"lower\"]", name: "aria-valuenow", value: "75" },
      { step: "press", key: "Tab" },
      { step: "expectFocus", selector: "[data-part=\"upper\"]" },
      { step: "press", key: "ArrowRight" },
      { step: "expectEvent", name: "valueChange", detail: [75, 76] },
      { step: "expectAttr", selector: "[data-part=\"upper\"]", name: "aria-valuenow", value: "76" },
      { step: "press", key: "Home" },
      { step: "expectEvent", name: "valueChange", detail: [75, 75] },
      { step: "expectAttr", selector: "[data-part=\"upper\"]", name: "aria-valuenow", value: "75" },
    ],
    [
      { step: "click", selector: "[data-part=\"track\"]" },
      { step: "expectEvent", name: "valueChange" },
    ],
  ],
  controls: {
    min: { type: "number", min: -1000, max: 1000, step: 1 },
    max: { type: "number", min: -1000, max: 1000, step: 1 },
    step: { type: "number", min: 0.1, max: 100, step: 0.1 },
    defaultValue: { type: "numbers" },
    label: { type: "string" },
  },
  credits: [],
  original: true,
};
