import type { Meta } from "../../../lib/meta";

export const meta: Meta = {
  slug: "aurora",
  title: "Aurora",
  category: "shaders",
  description: "Layered curtains of accent light standing on bowed lower borders, striated by vertical rays and dithered between a few tone steps on the GPU.",
  tags: ["aurora", "shader", "webgl", "background", "dither"],
  facets: ["animated", "background", "shader", "webgl", "dither"],
  wave: 3,
  animated: true,
  decorative: true,
  palette: ["fg", "accent", "bg"],
  controls: {
    speed: { type: "number", min: 0, max: 1, step: 0.05 },
    curtains: { type: "number", min: 2, max: 8, step: 1 },
    arc: { type: "number", min: 0, max: 1, step: 0.05 },
    height: { type: "number", min: 0.2, max: 1, step: 0.05 },
    horizon: { type: "number", min: 0.4, max: 1, step: 0.05 },
    sway: { type: "number", min: 0, max: 1, step: 0.05 },
    folds: { type: "number", min: 0, max: 1, step: 0.05 },
    rays: { type: "number", min: 0, max: 1, step: 0.05 },
    intensity: { type: "number", min: 0, max: 1, step: 0.05 },
    levels: { type: "number", min: 2, max: 16, step: 1 },
    pixel: { type: "number", min: 1, max: 6, step: 1, label: "Pixel (px)" },
    fps: { type: "number", min: 6, max: 60, step: 1 },
    paused: { type: "boolean" },
    seed: { type: "number", min: 0, max: 9999, step: 1 },
  },
  credits: [
    { relation: "technique", title: "Simulating the aurora", author: "Gladimir V. G. Baranoski et al.", url: "https://doi.org/10.1002/vis.304", license: "Paper" },
    { relation: "technique", title: "Interactive Volume Rendering Aurora on the GPU", author: "Orion Sky Lawlor and Jon Genetti", url: "https://hdl.handle.net/11025/1242", license: "Paper" },
    { relation: "technique", title: "Small-scale auroral arc distortions", author: "Thomas J. Hallinan and T. Neil Davis", url: "https://doi.org/10.1016/0032-0633(70)90007-3", license: "Paper" },
    { relation: "technique", title: "The development of the auroral substorm", author: "Syun-Ichi Akasofu", url: "https://doi.org/10.1016/0032-0633(64)90151-5", license: "Paper" },
    {
      relation: "technique",
      title: "Like an Outdoor Nightclub: Q&A on Pulsating Auroras",
      author: "NASA Science",
      url: "https://science.nasa.gov/blogs/the-sun-spot/2022/04/05/like-an-outdoor-nightclub-qa-on-pulsating-auroras/",
      license: "Public domain",
    },
    { relation: "technique", title: "Improving Noise", author: "Ken Perlin", url: "https://mrl.cs.nyu.edu/~perlin/paper445.pdf", license: "Paper" },
    { relation: "technique", title: "Ordered dithering", author: "Wikipedia", url: "https://en.wikipedia.org/wiki/Ordered_dithering", license: "Algorithm, no code" },
  ],
  original: false,
};
